services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    networks:
      - Shard
    depends_on:
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: start --log debug --user root --pass root memory
    networks:
      - Shard

networks:
  Shard:
    driver: bridge