"""modify superuser to be role enum

Revision ID: 49082d17d335
Revises: 1a31ce608336
Create Date: 2024-08-08 18:13:58.894159

"""
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49082d17d335'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = ENUM('user', 'premium', 'admin', name='userrole', create_type=True)
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', userrole_enum, nullable=False))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'role')
    ENUM(name="userrole").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
